name: "Terraform Deploy"
on: 
  push:
    branches:
      - master
      - dev

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: hashicorp/setup-terraform@v1
      
      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        id: init
        run: terraform init
        env:
          TF_VAR_github_token: ${{ secrets.GITHUB_TOKEN }}
          TF_VAR_agent_client_id: ${{ secrets.TF_VAR_agent_client_id }}
          TF_VAR_agent_client_secret: ${{ secrets.TF_VAR_agent_client_secret }}
          TF_VAR_subscription_id: ${{ secrets.TF_VAR_subscription_id }}
          TF_VAR_tenant_id: ${{ secrets.TF_VAR_tenant_id }}
          TF_VAR_storage_access_key: ${{ secrets.TF_VAR_tenant_id }}

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
        env:
          TF_VAR_github_token: ${{ secrets.GITHUB_TOKEN }}
          TF_VAR_agent_client_id: ${{ secrets.TF_VAR_agent_client_id }}
          TF_VAR_agent_client_secret: ${{ secrets.TF_VAR_agent_client_secret }}
          TF_VAR_subscription_id: ${{ secrets.TF_VAR_subscription_id }}
          TF_VAR_tenant_id: ${{ secrets.TF_VAR_tenant_id }}
          TF_VAR_storage_access_key: ${{ secrets.TF_VAR_storage_access_key }}

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        continue-on-error: true
        env:
          TF_VAR_github_token: ${{ secrets.GITHUB_TOKEN }}
          TF_VAR_agent_client_id: ${{ secrets.TF_VAR_agent_client_id }}
          TF_VAR_agent_client_secret: ${{ secrets.TF_VAR_agent_client_secret }}
          TF_VAR_subscription_id: ${{ secrets.TF_VAR_subscription_id }}
          TF_VAR_tenant_id: ${{ secrets.TF_VAR_tenant_id }}
          TF_VAR_storage_access_key: ${{ secrets.TF_VAR_storage_access_key }}

      # - name: "Terraform Apply"
      #   uses: hashicorp/terraform-github-actions@master
      #   with:
      #     tf_actions_version: 1.0.0
      #     tf_actions_subcommand: "apply"
      #     tf_actions_working_dir: "./"
      #     tf_actions_comment: true
      #   env:
      #     TF_VAR_github_token: ${{ secrets.GITHUB_TOKEN }}
      #     TF_VAR_agent_client_id: ${{ secrets.TF_VAR_agent_client_id }}
      #     TF_VAR_agent_client_secret: ${{ secrets.TF_VAR_agent_client_secret }}
      #     TF_VAR_subscription_id: ${{ secrets.TF_VAR_subscription_id }}
      #     TF_VAR_tenant_id: ${{ secrets.TF_VAR_tenant_id }}
